spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mySQL
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true