spring:
  application:
    name: demo
  datasource:
    url: jdbc:mariadb://localhost:3306/mySQL
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
          ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
  profiles:
    active: multiflex-jpa-local


server:
  port: 9999
  servlet:
    context-path: /api

